name: Build CentOS 7 Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Compile ser2net in CentOS 7 Docker
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace centos:7 /bin/bash -c "
            sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-* &&
            sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-* &&
            yum clean all &&
            
            yum install -y gcc make git autoconf automake libtool libyaml-devel libev-devel libmd-devel libcurl-devel &&

            cd /tmp &&
            git clone --depth 1 --branch v2.8.4 https://github.com/cminyard/gensio.git &&
            cd gensio &&
            ./autogen.sh &&
            ./configure --prefix=/usr/local &&
            make -j\$(nproc) &&
            make install &&
            ldconfig &&

            cd /workspace &&
            export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:\$PKG_CONFIG_PATH &&
            autoreconf -fi &&
            ./configure --prefix=/usr/local &&
            make -j\$(nproc)
          "

      - name: Fix Permissions
        run: sudo chown -R $USER:$USER .

      - name: Package Binary
        run: |
          tar -czvf ser2net-centos7.tar.gz ser2net ser2netconf

      - name: Upload Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ser2net-centos7.tar.gz
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
